version: "3.9"

services:
    web:
        ports:
            - 8000:8000
        networks:
            - webnet
        environment:
            BASE_URL: "${BASE_URL}"
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - node_modules:/app/node_modules
            - ./:/app
networks:
    webnet:
volumes:
    node_modules:
